
apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::975722656191:role/eksctl-kubernetes-github-actions-NodeInstanceRole-1K8Z3VEH87L2C
      username: system:node:{{EC2PrivateDNSName}}
      
  mapUsers: |
    - userarn: arn:aws:iam::975722656191:role/eksctl-kubernetes-github-actions
      username: kubernetes-github-actions
      groups:
        - system:masters

kind: ConfigMap
metadata:
  creationTimestamp: "2023-07-22T09:53:46Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "911"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: fbb5daca-c938-4117-954e-175218659147
